version: "3"
services:

  dockerrunner:
    image: gitlab/gitlab-runner
    environment:
      RUNNER_NAME: 'dockerrunner1'
      REGISTRATION_TOKEN: 'abc123'
      CI_SERVER_URL: 'http://192.168.50.3/'
      RUNNER_EXECUTOR: 'docker'
      DOCKER_IMAGE: 'microsoft/dotnet'
      DOCKER_PRIVILEGED: 'true'
      RUNNER_TAG_LIST: 'docker'
      REGISTER_LOCKED: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /vagrant/runners/shellrunner_setup.sh:/setup.sh
    entrypoint: '/bin/bash'
    command: '/setup.sh'

  shellrunner:
    image: gitlab/gitlab-runner
    environment:
      RUNNER_NAME: 'shellrunner1'
      REGISTRATION_TOKEN: abc123
      CI_SERVER_URL: 'http://192.168.50.3/'
      RUNNER_EXECUTOR: shell
      RUNNER_SHELL: bash
      DOCKER_PRIVILEGED: 'true'
      RUNNER_TAG_LIST: 'shell'
      REGISTER_LOCKED: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/docker:/usr/bin/docker:ro
      - /vagrant/runners/shellrunner_setup.sh:/setup.sh
    entrypoint: '/bin/bash'
    command: '/setup.sh'